[2024-05-05 20:21:10,438] INFO Expiring session 0x100001081480000, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2024-05-05 20:21:10,764] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group my_consumer_group in Stable state. Created a new member id rdkafka-00ec5d42-75c9-489d-9d31-e5b28e73a48f and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-05-05 20:21:11,125] WARN Session 0x100001081480000 for server localhost/[0:0:0:0:0:0:0:1]:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x100001081480000, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
[2024-05-05 20:21:10,870] INFO [LocalLog partition=topicget-2, dir=C:\kafka\kafka-logs] Rolled new log segment at offset 118 in 1055 ms. (kafka.log.LocalLog)
[2024-05-05 20:21:11,552] INFO [GroupCoordinator 0]: Member rdkafka-5e33a8d4-9b00-44f1-b651-06d410a32f5a in group my_consumer_group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-05-05 20:21:13,013] INFO [GroupCoordinator 0]: Preparing to rebalance group my_consumer_group in state PreparingRebalance with old generation 1 (__consumer_offsets-35) (reason: removing member rdkafka-5e33a8d4-9b00-44f1-b651-06d410a32f5a on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2024-05-05 20:21:13,593] INFO [GroupCoordinator 0]: Group my_consumer_group with generation 2 is now empty (__consumer_offsets-35) (kafka.coordinator.group.GroupCoordinator)
[2024-05-05 20:21:14,463] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. (org.apache.zookeeper.ClientCnxn)
[2024-05-05 20:21:14,899] INFO Socket connection established, initiating session, client: /[0:0:0:0:0:0:0:1]:50574, server: localhost/[0:0:0:0:0:0:0:1]:2181 (org.apache.zookeeper.ClientCnxn)
[2024-05-05 20:21:14,962] INFO [ProducerStateManager partition=topicget-2]Wrote producer snapshot at offset 118 with 0 producer ids in 1963 ms. (org.apache.kafka.storage.internals.log.ProducerStateManager)
[2024-05-05 20:21:15,913] INFO [UnifiedLog partition=topicget-2, dir=C:\kafka\kafka-logs] Deleting segment LogSegment(baseOffset=0, size=20643, lastModifiedTime=1714897569779, largestRecordTimestamp=Some(1714897569777)) due to log retention time 14400000ms breach based on the largest record timestamp in the segment (kafka.log.UnifiedLog)
[2024-05-05 20:21:16,222] INFO Invalid session 0x100001081480000 for client /[0:0:0:0:0:0:0:1]:50574, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2024-05-05 20:21:16,205] WARN Failed atomic move of C:\kafka\kafka-logs\topicget-2\00000000000000000000.index to C:\kafka\kafka-logs\topicget-2\00000000000000000000.index.deleted retrying with a non-atomic move (org.apache.kafka.common.utils.Utils)
java.nio.file.FileSystemException: C:\kafka\kafka-logs\topicget-2\00000000000000000000.index -> C:\kafka\kafka-logs\topicget-2\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:978)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:227)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:494)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:942)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:940)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:940)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:317)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1469)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1845)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1443)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1487)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3(LogManager.scala:1301)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3$adapted(LogManager.scala:1298)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:1298)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$2(LogManager.scala:573)
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:150)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
[2024-05-05 20:21:16,496] WARN Unable to reconnect to ZooKeeper service, session 0x100001081480000 has expired (org.apache.zookeeper.ClientCnxn)
[2024-05-05 20:21:16,569] WARN Session 0x100001081480000 for server localhost/[0:0:0:0:0:0:0:1]:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x100001081480000 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1438)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
[2024-05-05 20:21:16,500] INFO EventThread shut down for session: 0x100001081480000 (org.apache.zookeeper.ClientCnxn)
[2024-05-05 20:21:16,496] ERROR Error while deleting segments for topicget-2 in dir C:\kafka\kafka-logs (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.nio.file.FileSystemException: C:\kafka\kafka-logs\topicget-2\00000000000000000000.index -> C:\kafka\kafka-logs\topicget-2\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:982)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:227)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:494)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:942)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:940)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:940)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:317)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1469)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1845)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1443)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1487)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3(LogManager.scala:1301)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3$adapted(LogManager.scala:1298)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:1298)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$2(LogManager.scala:573)
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:150)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
	Suppressed: java.nio.file.FileSystemException: C:\kafka\kafka-logs\topicget-2\00000000000000000000.index -> C:\kafka\kafka-logs\topicget-2\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
		at java.base/java.nio.file.Files.move(Files.java:1432)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:978)
		... 25 more
[2024-05-05 20:21:16,726] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: Error while deleting segments for topicget-2 in dir C:\kafka\kafka-logs
Caused by: java.nio.file.FileSystemException: C:\kafka\kafka-logs\topicget-2\00000000000000000000.index -> C:\kafka\kafka-logs\topicget-2\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:982)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:227)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:494)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:942)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:940)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:940)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:317)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1469)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1845)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1443)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1487)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3(LogManager.scala:1301)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3$adapted(LogManager.scala:1298)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:1298)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$2(LogManager.scala:573)
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:150)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
	Suppressed: java.nio.file.FileSystemException: C:\kafka\kafka-logs\topicget-2\00000000000000000000.index -> C:\kafka\kafka-logs\topicget-2\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
		at java.base/java.nio.file.Files.move(Files.java:1432)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:978)
		... 25 more
[2024-05-05 20:21:16,775] WARN [ReplicaManager broker=0] Stopping serving replicas in dir C:\kafka\kafka-logs (kafka.server.ReplicaManager)
[2024-05-05 20:21:16,729] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2024-05-05 20:21:16,985] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-25, topicget-46, topicget-87, topicget-93, topicget-74, topicget-10, topicget-80, __consumer_offsets-22, topicget-45, topicget-90, topicget-79, topicget-97, __consumer_offsets-30, topicget-70, topicget-1, topicget-22, topicget-5, topicget-52, topicget-61, topicget-26, topicget-96, topicget-19, topicget-15, __consumer_offsets-8, __consumer_offsets-21, topicget-16, __consumer_offsets-4, topicget-32, topicget-73, __consumer_offsets-27, __consumer_offsets-7, topicget-78, __consumer_offsets-9, __consumer_offsets-46, topicget-75, topicget-94, topicget-35, topicget-31, topicget-95, __consumer_offsets-35, topicget-6, __consumer_offsets-41, topicget-71, __consumer_offsets-49, topicget-72, topicget-53, topicget-88, topicget-82, __consumer_offsets-33, __consumer_offsets-23, topicget-62, __consumer_offsets-16, topicget-24, __consumer_offsets-28, topicget-11, topicget-20, topicget-7, __consumer_offsets-47, topicget-2, topicget-89, topicget-8, __consumer_offsets-31, topicget-36, __consumer_offsets-36, topicget-91, __consumer_offsets-42, topicget-86, topicget-67, topicget-99, topicget-49, __consumer_offsets-3, topicget-37, topicget-83, __consumer_offsets-18, topicget-66, topicget-50, topicget-23, __consumer_offsets-37, topicget-27, topicget-65, my_topic-0, __consumer_offsets-15, __consumer_offsets-24, topicget-77, topicget-54, topicget-41, topicget-17, topicget-47, topicget-63, __consumer_offsets-38, __consumer_offsets-17, topicget-57, topicget-12, __consumer_offsets-48, topicget-68, topicget-33, topicget-28, topicget-3, topicget-29, __consumer_offsets-19, topicget-92, topicget-64, __consumer_offsets-11, topicget-76, topicget-51, topicget-58, topicget-59, topicget-42, topicget-48, __consumer_offsets-13, your_topic_name-0, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, topicget-38, topicget-69, topicget-98, topicget-14, topicget-40, topicget-18, topicget-0, topicget-13, topicget-9, topicsend-0, topicget-85, topicget-44, topicget-60, topicget-30, topicget-34, topicget-55, topicget-4, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, topicget-21, __consumer_offsets-39, topicget-25, __consumer_offsets-12, topicget-81, topicget-43, __consumer_offsets-45, topicget-84, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, topicget-56, __consumer_offsets-34, __consumer_offsets-10, topicget-39, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2024-05-05 20:21:16,875] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:17,053] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-25, topicget-46, topicget-87, topicget-93, topicget-74, topicget-10, topicget-80, __consumer_offsets-22, topicget-45, topicget-90, topicget-79, topicget-97, __consumer_offsets-30, topicget-70, topicget-1, topicget-22, topicget-5, topicget-52, topicget-61, topicget-26, topicget-96, topicget-19, topicget-15, __consumer_offsets-8, __consumer_offsets-21, topicget-16, __consumer_offsets-4, topicget-32, topicget-73, __consumer_offsets-27, __consumer_offsets-7, topicget-78, __consumer_offsets-9, __consumer_offsets-46, topicget-75, topicget-94, topicget-35, topicget-31, topicget-95, __consumer_offsets-35, topicget-6, __consumer_offsets-41, topicget-71, __consumer_offsets-49, topicget-72, topicget-53, topicget-88, topicget-82, __consumer_offsets-33, __consumer_offsets-23, topicget-62, __consumer_offsets-16, topicget-24, __consumer_offsets-28, topicget-11, topicget-20, topicget-7, __consumer_offsets-47, topicget-2, topicget-89, topicget-8, __consumer_offsets-31, topicget-36, __consumer_offsets-36, topicget-91, __consumer_offsets-42, topicget-86, topicget-67, topicget-99, topicget-49, __consumer_offsets-3, topicget-37, topicget-83, __consumer_offsets-18, topicget-66, topicget-50, topicget-23, __consumer_offsets-37, topicget-27, topicget-65, my_topic-0, __consumer_offsets-15, __consumer_offsets-24, topicget-77, topicget-54, topicget-41, topicget-17, topicget-47, topicget-63, __consumer_offsets-38, __consumer_offsets-17, topicget-57, topicget-12, __consumer_offsets-48, topicget-68, topicget-33, topicget-28, topicget-3, topicget-29, __consumer_offsets-19, topicget-92, topicget-64, __consumer_offsets-11, topicget-76, topicget-51, topicget-58, topicget-59, topicget-42, topicget-48, __consumer_offsets-13, your_topic_name-0, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, topicget-38, topicget-69, topicget-98, topicget-14, topicget-40, topicget-18, topicget-0, topicget-13, topicget-9, topicsend-0, topicget-85, topicget-44, topicget-60, topicget-30, topicget-34, topicget-55, topicget-4, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, topicget-21, __consumer_offsets-39, topicget-25, __consumer_offsets-12, topicget-81, topicget-43, __consumer_offsets-45, topicget-84, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, topicget-56, __consumer_offsets-34, __consumer_offsets-10, topicget-39, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
[2024-05-05 20:21:17,044] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2024-05-05 20:21:17,124] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:17,588] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:17,396] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@4b34fff9 (org.apache.zookeeper.ZooKeeper)
[2024-05-05 20:21:17,961] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:17,741] WARN [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-25,topicget-46,topicget-87,topicget-93,topicget-74,topicget-10,topicget-80,__consumer_offsets-22,topicget-45,topicget-90,topicget-79,topicget-97,__consumer_offsets-30,topicget-70,topicget-1,topicget-22,topicget-5,topicget-52,topicget-61,topicget-26,topicget-96,topicget-19,topicget-15,__consumer_offsets-8,__consumer_offsets-21,topicget-16,__consumer_offsets-4,topicget-32,topicget-73,__consumer_offsets-27,__consumer_offsets-7,topicget-78,__consumer_offsets-9,__consumer_offsets-46,topicget-75,topicget-94,topicget-35,topicget-31,topicget-95,__consumer_offsets-35,topicget-6,__consumer_offsets-41,topicget-71,__consumer_offsets-49,topicget-72,topicget-53,topicget-88,topicget-82,__consumer_offsets-33,__consumer_offsets-23,topicget-62,__consumer_offsets-16,topicget-24,__consumer_offsets-28,topicget-11,topicget-20,topicget-7,__consumer_offsets-47,topicget-2,topicget-89,topicget-8,__consumer_offsets-31,topicget-36,__consumer_offsets-36,topicget-91,__consumer_offsets-42,topicget-86,topicget-67,topicget-99,topicget-49,__consumer_offsets-3,topicget-37,topicget-83,__consumer_offsets-18,topicget-66,topicget-50,topicget-23,__consumer_offsets-37,topicget-27,topicget-65,my_topic-0,__consumer_offsets-15,__consumer_offsets-24,topicget-77,topicget-54,topicget-41,topicget-17,topicget-47,topicget-63,__consumer_offsets-38,__consumer_offsets-17,topicget-57,topicget-12,__consumer_offsets-48,topicget-68,topicget-33,topicget-28,topicget-3,topicget-29,__consumer_offsets-19,topicget-92,topicget-64,__consumer_offsets-11,topicget-76,topicget-51,topicget-58,topicget-59,topicget-42,topicget-48,__consumer_offsets-13,your_topic_name-0,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,__consumer_offsets-14,topicget-38,topicget-69,topicget-98,topicget-14,topicget-40,topicget-18,topicget-0,topicget-13,topicget-9,topicsend-0,topicget-85,topicget-44,topicget-60,topicget-30,topicget-34,topicget-55,topicget-4,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,topicget-21,__consumer_offsets-39,topicget-25,__consumer_offsets-12,topicget-81,topicget-43,__consumer_offsets-45,topicget-84,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,__consumer_offsets-29,topicget-56,__consumer_offsets-34,__consumer_offsets-10,topicget-39,__consumer_offsets-32,__consumer_offsets-40 and stopped moving logs for partitions  because they are in the failed log directory C:\kafka\kafka-logs. (kafka.server.ReplicaManager)
[2024-05-05 20:21:18,588] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:18,420] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2024-05-05 20:21:18,771] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:18,681] WARN Stopping serving logs in dir C:\kafka\kafka-logs (kafka.log.LogManager)
[2024-05-05 20:21:18,917] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:18,845] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2024-05-05 20:21:19,115] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (org.apache.kafka.server.util.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: The log dir C:\kafka\kafka-logs is already offline due to a previous IO exception.
[2024-05-05 20:21:19,054] ERROR Shutdown broker because all log dirs in C:\kafka\kafka-logs have failed (kafka.log.LogManager)
